name: DoomsdayVerify
main: fun.doomteam.verify.Main
version: 1.3
author: DoomsdaySociety
softdepend:
- ProtocolLib
- PlaceholderAPI
commands:
  doomsdayverify:
    descrption: main command
    aliases: [dv, ms]